apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  ACAPY_WALLET_KEY: "{{ randAlphaNum 32 | b64enc }}"
  MEDIATOR_AGENT_ADMIN_API_KEY: "{{ randAlphaNum 32 | b64enc }}"
  MEDIATOR_CONTROLLER_ADMIN_API_KEY: "{{ randAlphaNum 32 | b64enc }}"
type: Opaque
