apiVersion: v1
kind: Secret
metadata:  
  name: ocm-postgres-superuser
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  labels: 
    app.kubernetes.io/component: mediator-ocm                                                   
    app.kubernetes.io/instance: mediator                                                        
    app.kubernetes.io/managed-by: Helm                                                          
    app.kubernetes.io/name: mediator                                                            
    app.kubernetes.io/part-of: rse                                                              
    app.kubernetes.io/version: v0.0.7
type: Opaque                                                           
data:
  username: "YWRtaW4="
  password: "YmlyZHNhcmVudHJlYWw="